version: '3.8'
services:
  tracking-service:
    ports:
      - "5006:5005"            # map container 5005 to host 5006 to avoid conflict with order-service
    entrypoint:
      - "java"
      - "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005"
      - "-jar"
      - "app.jar"

